name: Build Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - name: Prepare Yarn
        run: corepack prepare yarn@4.9.1 --activate
      - name: Install dependencies and build
        run: |
          yarn install
          yarn build
      - name: Create ZIP
        run: |
          cd dist
          zip -r ../extension.zip *
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: extension.zip
